ifndef TARGET
TARGET=expfr5969
endif

CONTIKI = ../../..

CONTIKI_PROJECT = example-broadcast example-broadcast.hex

all: $(CONTIKI_PROJECT)

CONTIKI_WITH_RIME = 1

include $(CONTIKI)/Makefile.include
